mod context;
mod event;
mod hook;
mod plugin;
pub mod raw;
mod runtime;
mod rbr;
mod event_controller;
mod overlay;

pub use context::PluginContext;
pub use event::{
    Event,
    EventListener,
    EventRegistry,
    StartEvent,
    StopEvent,
    UpdateEvent,
    DrawEvent,
    EguiSetupEvent,
};
pub use plugin::RbrPlugin;
pub use runtime::{
    PluginError,
    PluginResult,
};

pub mod prelude {
    pub use crate::{
        Event,
        EventListener,
        PluginContext,
        PluginResult,
        RbrPlugin,
        StartEvent,
        UpdateEvent,
        StopEvent,
        DrawEvent,
        EguiSetupEvent
    };
    pub use crate::rbr::{
        GameMode,
        RbrReader,
        RbrWriter,
    };
}

pub use egui;
pub mod file_log {
    pub use log::{
        debug,
        error,
        info,
        trace,
        warn,
    };
}

unsafe extern "C" {
    fn cpp_create_plugin(game: *mut std::ffi::c_void) -> *mut std::ffi::c_void;
}


pub unsafe fn create_cpp_plugin(game: *mut std::ffi::c_void) -> *mut std::ffi::c_void {
    unsafe {
        cpp_create_plugin(game)
    }
}

// To hide the macro from plugin implementor
pub mod __private {
    pub use crate::{
        create_cpp_plugin,
        event::EventRegistry,
        runtime::{
            create,
            destroy,
            get_name,
        },
    };
}

// Register a Rust type as an RBR plugin.
/*
 * ---WARNING---
 * I don't know how to make good rust macros, so this was generated by GPT
 * Proceed with caution
 * ---WARNING---
 * This is for compatibility with .cpp
*/
#[macro_export]
macro_rules! export_plugin {
    (
        $plugin:ty,
        events = [$($event:ty),* $(,)?]
    ) => {
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn RBR_CreatePlugin(game: *mut std::ffi::c_void) -> *mut std::ffi::c_void {
            unsafe {
                $crate::__private::create_cpp_plugin(game)
            }
        }

        #[unsafe(no_mangle)]
        pub extern "C" fn rust_plugin_create(game: *mut std::ffi::c_void) -> *mut std::ffi::c_void {
            let mut events = $crate::__private::EventRegistry::<$plugin>::new();
            $(events.register::<$event>();)*

            $crate::__private::create::<$plugin>(events)
        }

        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn rust_plugin_destroy(state: *mut std::ffi::c_void) {
            unsafe {
                $crate::__private::destroy::<$plugin>(state);
            }
        }

        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn rust_plugin_get_name(state: *mut std::ffi::c_void) -> *const std::ffi::c_char {
            unsafe {
                $crate::__private::get_name::<$plugin>(state)
            }
        }

        #[unsafe(no_mangle)]
        pub extern "C" fn rust_plugin_draw_frontend_page(state: *mut std::ffi::c_void) {
        }

        #[unsafe(no_mangle)]
        pub extern "C" fn rust_plugin_draw_results_ui(
            _state: *mut std::ffi::c_void,
        ) {
        }

        #[unsafe(no_mangle)]
        pub extern "C" fn rust_plugin_handle_frontend_events(
            state: *mut std::ffi::c_void,
            keyboard: std::ffi::c_char,
            up: u8,
            down: u8,
            left: u8,
            right: u8,
            select: u8
        ) {}

        #[unsafe(no_mangle)]
        pub extern "C" fn rust_plugin_tick_frontend_page(
            state: *mut std::ffi::c_void,
            delta: f32,
        ) {}

        #[unsafe(no_mangle)]
        pub extern "C" fn rust_plugin_stage_started(
            state: *mut std::ffi::c_void,
            map: i32,
            player_name: *const std::ffi::c_char,
            false_start: u8,
        ) {}

        #[unsafe(no_mangle)]
        pub extern "C" fn rust_plugin_handle_results(
            state: *mut std::ffi::c_void,
            checkpoint1: f32,
            checkpoint2: f32,
            finish_time: f32,
            player_name: *const std::ffi::c_char,
        ) {}

        #[unsafe(no_mangle)]
        pub extern "C" fn rust_plugin_checkpoint(
            state: *mut std::ffi::c_void,
            checkpoint_time: f32,
            checkpoint_id: i32,
            player_name: *const std::ffi::c_char,
        ) {}
    };
}