pub const PTR_TYREVALUE_WCHAR_FIRESTONE: usize = 0x743BA0;
pub const PTR_TYREVALUE_WCHAR_BRIDGESTONE: usize = 0x743BB4;
pub const PTR_TYREVALUE_WCHAR_PIRELLI: usize = 0x743BCC;
pub const PTR_TYREVALUE_WCHAR_MICHELIN: usize = 0x743BDC;


pub const RBRMENUSYSTEM_NUM_OF_MENUS: usize = 89;

pub const RBRMENUIDX_STARTUP: usize = 82;
pub const RBRMENUIDX_STARTUP_CREATEPROFILE: usize = 23;

pub const RBRMENUIDX_MAIN: usize = 00;

pub const RBRMENUIDX_RALLYSCHOOL: usize = 18;
pub const RBRMENUIDX_RALLYSCHOOL_BASICDRIVING: usize = 19;
pub const RBRMENUIDX_RALLYSCHOOL_ADVANCEDTECH: usize = 20;
pub const RBRMENUIDX_RALLYSCHOOL_TRANSMISSION: usize = 21;

pub const RBRMENUIDX_QUICKRALLY: usize = 03;
pub const RBRMENUIDX_QUICKRALLY_STAGE_GB: usize = 05;
pub const RBRMENUIDX_QUICKRALLY_STAGE_JAP: usize = 08;
pub const RBRMENUIDX_QUICKRALLY_STAGE_FIN: usize = 04;
pub const RBRMENUIDX_QUICKRALLY_STAGE_USA: usize = 09;
pub const RBRMENUIDX_QUICKRALLY_STAGE_FRA: usize = 07;
pub const RBRMENUIDX_QUICKRALLY_STAGE_AUS: usize = 06;
pub const RBRMENUIDX_QUICKRALLY_WEATHER: usize = 10;
pub const RBRMENUIDX_QUICKRALLY_CARS: usize = 02;
pub const RBRMENUIDX_QUICKRALLY_TRANSMISSION: usize = 11;
pub const RBRMENUIDX_QUICKRALLY_SETUP: usize = 12;

pub const RBRMENUIDX_RALLYSEASON: usize = 36;
pub const RBRMENUIDX_RALLYSEASON_CARDAMAGE: usize = 37;
pub const RBRMENUIDX_RALLYSEASON_TEAMOFFERS: usize = 24;
pub const RBRMENUIDX_RALLYSEASON_TRANSMISSION: usize = 43;
pub const RBRMENUIDX_RALLYSEASON_TRIAL: usize = 25;
pub const RBRMENUIDX_RALLYSEASON_WELCOME: usize = 27;
pub const RBRMENUIDX_RALLYSEASON_SEASONCONTINUE: usize = 26;
pub const RBRMENUIDX_RALLYSEASON_SEASONDATA: usize = 49;

pub const RBRMENUIDX_MULTIPLAYER: usize = 57;
pub const RBRMENUIDX_MULTIPLAYER_SEATTYPE: usize = 58;
pub const RBRMENUIDX_MULTIPLAYER_PACECARS: usize = 77;
pub const RBRMENUIDX_MULTIPLAYER_SKILLLEVEL: usize = 64;
pub const RBRMENUIDX_MULTIPLAYER_COUNTRY: usize = 65;
pub const RBRMENUIDX_MULTIPLAYER_STAGE: usize = 68;
pub const RBRMENUIDX_MULTIPLAYER_WEATHER: usize = 66;
pub const RBRMENUIDX_MULTIPLAYER_CARS_P1: usize = 59;
pub const RBRMENUIDX_MULTIPLAYER_CARS_P2: usize = 60;
pub const RBRMENUIDX_MULTIPLAYER_CARS_P3: usize = 61;
pub const RBRMENUIDX_MULTIPLAYER_CARS_P4: usize = 62;
pub const RBRMENUIDX_MULTIPLAYER_TRANSMISSION: usize = 78;
pub const RBRMENUIDX_MULTIPLAYER_PLAYERFINISHED: usize = 79;
pub const RBRMENUIDX_MULTIPLAYER_REGISTERPLAYER: usize = 63;

pub const RBRMENUIDX_RBRCHALLENGE_WELCOME: usize = 13;
pub const RBRMENUIDX_RBRCHALLENGE_STAGE: usize = 15;
pub const RBRMENUIDX_RBRCHALLENGE_CARS: usize = 14;
pub const RBRMENUIDX_RBRCHALLENGE_TRANSMISSION: usize = 16;
pub const RBRMENUIDX_RBRCHALLENGE_SETUP: usize = 17;

pub const RBRMENUIDX_DRIVERPROFILE: usize = 81;
pub const RBRMENUIDX_DRIVERPROFILE_LOADREPLAY: usize = 85;

pub const RBRMENUIDX_CREDITS: usize = 22;